DROP TABLE IF EXISTS `Artikel`;
DROP TABLE IF EXISTS `Keyword`;
DROP TABLE IF EXISTS `Ausgabe`;
DROP TABLE IF EXISTS `Loci`;
DROP TABLE IF EXISTS `Sprache`;
DROP TABLE IF EXISTS `Publisher`;
DROP TABLE IF EXISTS `Gattung`;
DROP TABLE IF EXISTS `Text/Bild`;
DROP TABLE IF EXISTS `Person`;
DROP TABLE IF EXISTS `Nation`;

