# SET DATABASE COLLATION "Latin1_General";
# CREATE SCHEMA PUBLIC AUTHORIZATION DBA;
CREATE TABLE `departments`(`dep_id` INTEGER NOT NULL  ,`dep_name` VARCHAR(100));
CREATE TABLE `persons`(`person_id` INTEGER NOT NULL  ,`name` VARCHAR(100),`department` INTEGER);
# CREATE USER SA PASSWORD "";
# GRANT DBA TO SA;
# SET WRITE_DELAY 60;
# SET SCHEMA PUBLIC;
INSERT INTO `departments` VALUES(0,'Abteilung 07');
INSERT INTO `departments` VALUES(1,'Müller Institut');
INSERT INTO `departments` VALUES(2,'歌德學院');
INSERT INTO `persons` VALUES(0,'Viktoria',1);
INSERT INTO `persons` VALUES(1,'Johannes',0);
INSERT INTO `persons` VALUES(2,'Markus',1);
INSERT INTO `persons` VALUES(3,'Vicent',2);
INSERT INTO `persons` VALUES(4,'Daniel',1);
INSERT INTO `persons` VALUES(5,'Elisabeth',2);
INSERT INTO `persons` VALUES(6,'Marielle',0);
INSERT INTO `persons` VALUES(7,'Maria',1);
INSERT INTO `persons` VALUES(8,'Rudolf',2);
INSERT INTO `persons` VALUES(9,'Katharina',2);
INSERT INTO `persons` VALUES(10,'Richard',0);
INSERT INTO `persons` VALUES(11,'Viola',1);
ALTER TABLE `departments` ADD PRIMARY KEY(`dep_id`);
ALTER TABLE `persons` ADD PRIMARY KEY(`person_id`);
ALTER TABLE `persons` ADD CONSTRAINT `SYS_FK_60` FOREIGN KEY(`department`) REFERENCES `departments`(`dep_id`);
ALTER TABLE `departments` MODIFY `dep_id` INTEGER NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=3;
ALTER TABLE `persons` MODIFY `person_id` INTEGER NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=12;